FoodRecipes/Controllers/IngredientsController.cs
namespace FoodRecipes.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;
    using FoodRecipes.Services.Ingredients;
    using FoodRecipes.Infrastructure;
    using FoodRecipes.Models.Ingredients;
    using FoodRecipes.Services.Sellers;

    public class IngredientsController : Controller
    {
        private readonly IIngredientService ingredients;
        private readonly ISellerService sellers;

        public IngredientsController(
            IIngredientService ingredients,
            ISellerService sellers)
        {
            this.ingredients = ingredients;
            this.sellers = sellers;
        }

        // HTTPGet
        public IActionResult All([FromQuery] AllIngredientsQueryModel query)
        {
            var queryResult = this.ingredients.All(
                query.Name,
                query.SearchTerm,
                query.Sorting,
                query.CurrentPage,
                AllIngredientsQueryModel.IngredientsPerPage);

            var ingredientNames = this.ingredients.AllIngredientNames();

            query.Names = ingredientNames;
            query.TotalRecipes = queryResult.TotalIngredients;
            query.Ingredients = queryResult.Ingredients;

            return View(query);
        }

        [Authorize]
        public IActionResult MyIngredients()
        {
            var myIngredients = this.ingredients.GetIngredientsByUser(this.User.GetId());

            return View(myIngredients);
        }

        [Authorize]
        public IActionResult Add()
        {
            if (!this.sellers.IsSeller(this.User.GetId()))
            {
                return RedirectToAction(nameof(SellersController.Become), "Sellers");
            }

            return View(new IngredientFormModel
            {
                Categories = this.ingredients.AllIngredientCategories()
            });
        }

        [HttpPost]
        [Authorize]
        public IActionResult Add(IngredientFormModel ingredient)
        {
            var sellerId = this.sellers.GetSellerIdByUserId(this.User.GetId());

            if (sellerId == 0)
            {
                return RedirectToAction(nameof(SellersController.Become), "Sellers");
            }

            if (!this.ingredients.CategoryExists(ingredient.CategoryId))
            {
                this.ModelState.AddModelError(nameof(ingredient.CategoryId), "Category does not exists.");
            }

            if (!ModelState.IsValid)
            {
                ingredient.Categories = this.ingredients.AllIngredientCategories();

                return View(ingredient);
            }

            this.ingredients.Create(
                ingredient.Name,
                ingredient.ImageUrl,
                ingredient.CategoryId,
                sellerId);

            return RedirectToAction(nameof(All));
        }

        [Authorize]
        public IActionResult Edit(int id)
        {
            var userId = this.User.GetId();

            if (!this.sellers.IsSeller(userId) && !User.IsAdmin())
            {
                return RedirectToAction(nameof(SellersController.Become), "Sellers");
            }

            var ingredient = this.ingredients.Details(id);

            if (ingredient.UserId != userId && !User.IsAdmin())
            {
                return Unauthorized();
            }

            return View(new IngredientFormModel
            {
                Name = ingredient.Name,
                ImageUrl = ingredient.ImageUrl,
                CategoryId = ingredient.CategoryId,
                Categories = this.ingredients.AllIngredientCategories()
            });
        }

        [HttpPost]
        [Authorize]
        public IActionResult Edit(int id, IngredientFormModel ingredient)
        {
            var sellerId = this.sellers.GetSellerIdByUserId(this.User.GetId());

            if (sellerId == 0 && !User.IsAdmin())
            {
                return RedirectToAction(nameof(SellersController.Become), "Sellers");
            }

            if (!this.ingredients.CategoryExists(ingredient.CategoryId))
            {
                this.ModelState.AddModelError(nameof(ingredient.CategoryId), "Category does not exists.");
            }

            if (!ModelState.IsValid)
            {
                ingredient.Categories = this.ingredients.AllIngredientCategories();

                return View(ingredient);
            }

            if (!this.ingredients.IngredientIsFromSeller(id, sellerId) && !User.IsAdmin())
            {
                return BadRequest();
            }

            this.ingredients.Edit(
                id,
                ingredient.Name,
                ingredient.ImageUrl,
                ingredient.CategoryId);

            return RedirectToAction(nameof(All));
        }


        [Route("{id}/ingredients")]
        public IActionResult Details(int id)
        {
            var ingredient = this.ingredients.Details(id);

            return View(ingredient);
        }
    }
}

FoodRecipes/Controllers/RecipesController.cs
namespace FoodRecipes.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;
    using FoodRecipes.Services.Recipes;
    using FoodRecipes.Infrastructure;
    using FoodRecipes.Services.Cooks;
    using FoodRecipes.Models.Recipes;
    using AutoMapper;

    public class RecipesController : Controller
    {
        private readonly IRecipeService recipes;
        private readonly ICookService cooks;
        private readonly IMapper mapper;

        public RecipesController(
            IRecipeService recipes,
            ICookService cooks,
            IMapper mapper)
        {
            this.recipes = recipes;
            this.cooks = cooks;
            this.mapper = mapper;
        }

        // HTTPGet
        public IActionResult All([FromQuery] AllRecipesQueryModel query)
        {
            var queryResult = this.recipes.All(
                query.Name,
                query.SearchTerm,
                query.Sorting,
                query.CurrentPage,
                AllRecipesQueryModel.RecipesPerPage);

            var recipeNames = this.recipes.AllRecipeNames();

            query.Names = recipeNames;
            query.TotalRecipes = queryResult.TotalRecipes;
            query.Recipes = queryResult.Recipes;

            return View(query);
        }

        [Authorize]
        public IActionResult MyRecipes()
        {
            var myRecieps = this.recipes.GetRecipesByUser(this.User.GetId());

            return View(myRecieps);
        }

        [Authorize]
        public IActionResult Add()
        {
            if (!this.cooks.IsCook(this.User.GetId()))
            {
                return RedirectToAction(nameof(CooksController.Become), "Cooks");
            }

            return View(new RecipeFormModel
            {
                Categories = this.recipes.AllRecipeCategories()
            });
        }

        [HttpPost]
        [Authorize]
        public IActionResult Add(RecipeFormModel recipe)
        {
            var cookId = this.cooks.GetCookIdByUserId(this.User.GetId());

            if (cookId == 0)
            {
                return RedirectToAction(nameof(CooksController.Become), "Cooks");
            }

            if (!this.recipes.CategoryExists(recipe.CategoryId))
            {
                this.ModelState.AddModelError(nameof(recipe.CategoryId), "Category does not exists.");
            }

            if (!ModelState.IsValid)
            {
                recipe.Categories = this.recipes.AllRecipeCategories();

                return View(recipe);
            }

            this.recipes.Create(
                recipe.Name,
                recipe.Ingredients,
                recipe.Directions,
                recipe.ImageUrl,
                recipe.CookingTime,
                recipe.CategoryId,
                cookId);

            return RedirectToAction(nameof(All));
        }

        [Authorize]
        public IActionResult Edit(int id)
        {
            var userId = this.User.GetId();

            if (!this.cooks.IsCook(userId) && !User.IsAdmin())
            {
                return RedirectToAction(nameof(CooksController.Become), "Cooks");
            }

            var recipe = this.recipes.Details(id);

            if (recipe.UserId != userId && !User.IsAdmin())
            {
                return Unauthorized();
            }

            var recipeForm = this.mapper.Map<RecipeFormModel>(recipe);

            recipeForm.Categories = this.recipes.AllRecipeCategories();

            return View(recipeForm);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Edit(int id, RecipeFormModel recipe)
        {
            var cookId = this.cooks.GetCookIdByUserId(this.User.GetId());

            if (cookId == 0 && !User.IsAdmin())
            {
                return RedirectToAction(nameof(CooksController.Become), "Cooks");
            }

            if (!this.recipes.CategoryExists(recipe.CategoryId))
            {
                this.ModelState.AddModelError(nameof(recipe.CategoryId), "Category does not exists.");
            }

            if (!ModelState.IsValid)
            {
                recipe.Categories = this.recipes.AllRecipeCategories();

                return View(recipe);
            }

            if (!this.recipes.RecipeIsFromCook(id, cookId) && !User.IsAdmin())
            {
                return BadRequest();
            }

            this.recipes.Edit(
                id,
                recipe.Name,
                recipe.Ingredients,
                recipe.Directions,
                recipe.ImageUrl,
                recipe.CookingTime,
                recipe.CategoryId);

            return RedirectToAction(nameof(All));
        }


        [Route("{id}")]
        public IActionResult Details(int id)
        {
            var recipe = this.recipes.Details(id);

            return View(recipe);
        }
    }
}

FoodRecipes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - The Best Food Recipes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FoodRecipes</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (!User.IsAdmin())
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Recipes" asp-action="Add">Add Recipe</a>
                            </li>
                        }
                        @if (!User.IsAdmin())
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Ingredients" asp-action="Add">Add Ingredient</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Recipes" asp-action="All">All Recipes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ingredients" asp-action="All">Buy Ingredients</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.UtcNow.Year - FoodRecipes
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>